apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tazanews-online-tls
spec:
  secretName: tazanews-online
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: tazanews.online
  dnsNames:
    - tazanews.online
    - www.tazanews.online
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - tazanews.online
          - www.tazanews.online
